server:
  port: 8088
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/ysframework?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        naming:
            #驼峰命名法不修改为_
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: update
      show-sql: true
      #不加这句则默认为myisam引擎 索引长度会限制在1000以内
      #建表指定UTF-8 否则表不能存中文
      database-platform: cn.pxy.ysframework.config.MySQL5DialectUTF8
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true